apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp 
spec:
  repicas : 2
  selector:
    matchLabels:
      app: myapp 
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
      - name: myapp 
        image: muammerarpa/myapp 
        ports:
        - containerPort: 80
